### ISSUE TITLE
link is wrong

### ISSUE THREAD

**Issue by ydnaandy123** [dongb5/GAN_Time_Line#1]
Very useful document! Thank you so much
The arxiv link of "2017-03-29 | [CV App] Kiana Ehsani, et al. "SeGAN: Segmenting and Generating the Invisible". SeGAN" seems wrong?

**Comment by dongb5** [comment]
@ydnaandy123 Good catch! I will fix it ASAP. Thank you!

**Comment by Tymyan1** [comment]
2017-03-29 | [CV App] Jianmin Bao et al. "CVAE-GAN: Fine-Grained Image Generation through Asymmetric Training". CVAE-GAN 
The link is pointing towards SeGAN now

**Comment by dongb5** [comment]
@Tymyan1 Thanks! I have deleted the arXiv version item since CVAE-GAN has a ICCV version.
